version: '3'
services:
  mongo:
    container_name: testing-mongo
    image: mongo
    environment:
      - MONGODB_SMALL_FILES=true
      - MONGODB_DISABLE_BACKGROUND_WRITES=true
    ports:
       - 27017:27017
    command: "mongod"
    healthcheck:
      test: ["CMD-SHELL", "mongo --quiet 'localhost/test' --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      interval: 10s
    volumes: 
      - ~/mongo/data:/data/db

  api:
    container_name: testing-api
    build: .
    env_file: 
      - .ci.env
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
