version: 2.1

jobs:
  build:
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - checkout
      - run: docker-compose -f docker-compose.ci.yml build

  lint:
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - checkout
      - run: docker-compose -f docker-compose.ci.yml run --rm api bin/lint

  unit-tests:
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - checkout
      - run: docker-compose -f docker-compose.ci.yml run --rm api bin/unit

  integration-tests:
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - checkout
      - run: docker-compose -f docker-compose.ci.yml up -d mongo
      - run: docker-compose -f docker-compose.ci.yml up -d api
      - run: docker-compose -f docker-compose.ci.yml run --rm api bin/integration

workflows:
  api-pipeline:
    jobs:
      - build
      - lint:
          requires:
            - build
      - unit-tests:
          requires:
            - build
      - integration-tests:
          requires:
            - build
